name: "addimg_003"

on:
  workflow_call:
    inputs:
      rep:
        type: string
      nam:
        type: string
      env:
        type: string
      ver:
        type: string
      opt:
        type: string

permissions:
  contents: read
  packages: write

jobs:
  runs-on: ubuntu-latest
  steps:
    call:
    - uses: cnnmmd/manage_docenv/.github/workflows/addarc_001.yml@master
      with:
        rep: ${{ inputs.rep }}
        nam: ${{ inputs.nam }}
        env: ${{ inputs.env }}
        ver: ${{ inputs.ver }}
        opt: ${{ inputs.opt }}
        arc: amd64
    - uses: cnnmmd/manage_docenv/.github/workflows/addarc_001.yml@master
      with:
        rep: ${{ inputs.rep }}
        nam: ${{ inputs.nam }}
        env: ${{ inputs.env }}
        ver: ${{ inputs.ver }}
        opt: ${{ inputs.opt }}
        arc: arm64
    - run: |
        tag="ghcr.io/${{ inputs.rep }}/${{ inputs.nam }}/${{ inputs.env }}:${{ inputs.ver }}"
        docker buildx imagetools create \
        ${tag}-${{ 'amd64' }} \
        ${tag}-${{ 'arm64' }} \
        --tag ${tag}
